# Generated by Django 5.2.13 on 2026-04-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalentry',
            name='content_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalentry',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
